kk-digital/KCG

Assets/Scenes/GameManager.cs
=> Setup Main Loop #10

Assets/Libraries/PRNG/Mt19937.cs
Pretty much straight-forward conversion of the c version of mt19937 that was provided to C#.
=> conversion of the C version of mt19937 to C#

Assets/Scenes/PNGTest.unity, Assets/Scripts/ImageTest.cs, Assets/src/asset-loaders/SpriteSheetImageLoader.cs, Assets/src/game-engine/png-loader/LoaderData.cs, Assets/src/game-engine/png-loader/PngProperties.cs
Test to take each sprite from the spritesheet and display
=> WIP Taking sprites from Spritesheet

Assets/Scenes/Game.unity, Assets/Scenes/MapLoaderTest-MoonBunker.unity, Assets/Scenes/PNGTest.unity, Assets/Scenes/Test.unity, Assets/Scripts/GameLoop.cs, Assets/Scripts/GameLoop.cs.meta
https://github.com/kk-digital/kcg/issues/40
=> GameLoopScript

Assets/Libraries/PerlinNoise/PerlinField2D.cs, Assets/Libraries/PerlinNoise/PerlinField3D.cs, Assets/Libraries/PerlinNoise/PerlinOctave2D.cs, Assets/Libraries/PerlinNoise/PerlinOctave3D.cs
I also cleaned up that code to some extent as some parts were very messy and unreadable.
=> Ported Perlin Noise library from C++ for #45

Assets/Libraries/BigGustave/pixelgridTransparent.png.meta, Assets/Libraries/PerlinNoise.meta, Assets/Libraries/PerlinNoise/PerlinField2D.cs.meta, Assets/Libraries/PerlinNoise/PerlinField3D.cs.meta, Assets/Libraries/PerlinNoise/PerlinOctave2D.cs.meta, Assets/Libraries/PerlinNoise/PerlinOctave3D.cs.meta, Assets/Scenes/PixelPerfectCameraTest.unity.meta, Assets/Scripts/GameLoop.cs, Assets/Scripts/PixelPerfectCameraTestTool.cs.meta, Assets/Scripts/PixelPerfectGrid.cs, Assets/Scripts/PixelPerfectGrid.cs.meta, Assets/Scripts/PixelSnap.cs, Assets/Scripts/PixelSnap.cs.meta, Assets/Utility.meta, Assets/Utility/XorShift.meta, Assets/Utility/XorShift/XorShift.cs.meta
fixed some scripts inside src/Scripts that did not register properly to the new SceneManager class
=> fixing some compile errors

Assets/Scenes/PNGTest.unity, Assets/Scripts/ImageTest.cs, Assets/src/asset-loaders/SpriteSheetImageLoader.cs, Assets/src/asset-loaders/TileSpriteImageLoader.cs, Assets/src/game-engine/png-loader/PngProperties.cs, Assets/src/game-engine/png-loader/SpriteSheetProperties.cs
-Cleaned up some unnecessary lines of code
-Found bug on the registration of the scene, which I have commented for now on ImageTest.cs
=> Cleaned up some unnecessary lines of code

Assets/src/SceneManager/SceneManager.cs, Assets/src/Utility.meta, Assets/src/Utility/FileLoader.meta, Assets/src/Utility/FileLoader/FileLoadingManager.cs, Assets/src/Utility/FileLoader/FileLoadingManager.cs.meta
Created the basic FileLoadingManager that will handle loading files into memory.
An integer will be used for refrencing a given file resource
NOTE that this is the first version of the FileLoadingManager class
the class still lacks some features like:
-unloading fileData.
-reusing fileIds
-refreshing files when they are changes on the fly
=> uncomplete version of FileLoadingManager

Assets/Scripts/ImageTest.cs, Assets/src/TilePropertiesManager/PlanetTileProperties.cs, Assets/src/TilePropertiesManager/TilePropertiesManager.cs, Assets/src/asset-loaders/SpriteSheetImageLoader.cs, Assets/src/enums/PlanetTileMap.cs, Assets/src/enums/TileDrawTypeProperties.cs, Assets/src/game-engine/png-loader/LoaderData.cs
**Added some modifiable functions on PlanetTileProperties**
-In case after the first newly created tileproperty with already properties being set,
you might want to change it anytime by accessing the id of a tile
-Replacing some private access modifiers to public
-PlanetTileProperties Constructor
=> PlanetTileProperties Commits

Assets/src/Utility/FileLoader/FileLoadingManager.cs
I added more features to the FileLoadingManager:
-Unloading a Filedata from ram, can be done by specifying the id or the file name.
-Reusing previously unloaded fileId so that we dont run out of ids.
=> FileLoadingManager more features issue #42

Assets/src/PlanetTileMap/TmxMapFileLoader/TmxMapFileLoader.cs, Assets/src/TilePropertiesManager/TilePropertiesManager.cs
-Fixed tileProperties errors
-MapLoaderTest can now be played
=> Fixed tileProperties errors

Assets/Scenes/PixelPerfectCameraTest.unity, Assets/Scripts/PixelPerfectGrid.cs, Assets/Scripts/PixelSnap.cs
Some null pointer checks added to keep code safe.
=> Pixel Perfect Camera Scene Code Edited

Assets/Scenes/MapLoaderTest-MoonBunker.unity, Assets/src/PlanetTileMap/Core/Builders/QuadsBuilder.cs, Assets/src/PlanetTileMap/TmxMapFileLoader/TmxMapFileLoader.cs, Assets/src/TilePropertiesManager/TilePropertiesManager.cs, Assets/src/game-manager/GameManager.cs
-Changing public variables to PascalCases, such as variable "Instance"
-Resolved lines of errors
=> Changing public variables into PascalCases

Assets/Scenes/OpenGLRenderingTestScene.unity, Assets/Scripts/GLTestCube.cs, Assets/Shaders/GLSkyboxTestMaterial.mat, Assets/Shaders/GLSkyboxTestShader.shader, Assets/Shaders/GLTestMaterial.mat, Assets/Shaders/GLTestShader.shader, Documents/disabling-unity-modules.md
OpenGL, GLSL test scene added. 3 geometric shapes colored with GLSL shading. Issue #85
=> OpenGL Support: GLSL Test Scene Added #85

Assets/Scripts/SceneManager.cs
Added:
instantiate the singelton SceneManager upon request
=> quick fix to SceneManager

Assets/Scenes/PixelPerfectCameraTest.unity
Test scene wasn't working. Pixel Perfect Camera Test Scene Edited to Work With New Tile Render System.
=> Pixel Perfect Camera Test Scene Edited to Work With New Tile Render System

Assets/Scripts/SceneManager.cs, Assets/src/Library.meta
using AppComponent Api for SceneManager instead of 
_instance = new SceneManager()
=> SceneManager AddComponent Api

Assets/src/Enum/PlanetTileMap.cs, Assets/src/GameManager/GameState.cs, Assets/src/GameManager/GameState.cs.meta, Assets/src/Library.meta, Assets/src/PlanetTileMap/PlanetTileMap.cs, Assets/src/TileProperties/TileCreationApi.cs, Assets/src/TileProperties/TileProperties.cs, Assets/src/TileSpriteAtlas/SpriteAtlas.cs, Assets/src/TileSpriteAtlas/SpriteAtlasManager.cs
TileCreationApi is now online 
Can be found in GameState.TileCreationApi
an example would be
GameState.TileCreationApi.CreateTile(0);
GameState.TileCreationApi.SetTileTexture(1, 10, 2);
GameState.TileCreationApi.SetTileName("Regolith");
GameState.TileCreationApi.EndTile();
The way you get a tile is calling
GameState.TileCreationApi.GetTileProperties(tileId);
or
GameState.TileCreationApi.GetTileProperties(name);
=> TileCreationApi implementation

Assets/Scenes/OpenGLRenderingTestScene.unity, Assets/Shaders/GLSkyboxTestMaterial.mat, Assets/Shaders/GLTestMaterial.mat
OpenGL Shader Test Scene Bugs Fixed
=> OpenGL Test Scene Bugs Fixed

Assets/Scripts/TilesRenderer.cs, Assets/src/GameManager/GameManager.cs, Assets/src/TileSpriteAtlas/SpriteAtlas.cs, Assets/src/TileSpriteAtlas/SpriteAtlasManager.cs, Assets/src/TileSpriteLoader/TileSpriteLoader.cs
-Fixed the blit code
-Added a quick and simple rendering code for a flat tile surface
-Changed some other stuff
-Added the blit8-blit16 functions and done fews tests. they are now working.
=> Blit32 Blit16 Blit8

Assets/Scripts/CameraMove.cs, Assets/Scripts/TilesRenderer.cs, Assets/src/GameManager/GameState.cs, Assets/src/TileProperties/TileCreationApi.cs, Assets/src/TileSpriteAtlas/SpriteAtlasManager.cs
created some tiles for testing.
fixed a bug in the blit code.
=> fixed the blit code and created some tiles for testing, using the api

Assets/src/game-engine/CameraInfo.cs
Get/Set/Information functions added. Informations are visible on the inspector. A few thing left to do. Issue #86 (https://github.com/kk-digital/kcg/issues/86)
=> Camera Information Class Issue #86: Get/Set/Info Implemented

Assets/Scripts/CameraInfo.cs
All camera information saved in a struct, so we can save or do anything later. Script moved to Assets/Scripts. Ticket #86
=> Camera Information Class Issue #86: Information Saved In a Struct

Assets/Scripts/TilesRenderer.cs, Assets/src/PlanetTileMap/MeshBuilder.cs, Assets/src/PlanetTileMap/PlanetTileMap.cs, Assets/src/PlanetTileMap/PlanetTileMapChunk.cs, Assets/src/TileProperties/PlanetTile.cs, Assets/src/TileSpriteAtlas/SpriteAtlasManager.cs
-Test render using PlanetTileMap and some random static tiles we have right.
-Some improvements to the simple rendering we have
-Removed MeshBuilder, we dont need that
=> Using the PlanetTileMap to render tiles on screen

Assets/Scenes/MapLoaderTest-MoonBunker.unity, Assets/Scenes/PixelPerfectCameraTest.unity, Assets/Scripts/CameraInfo.cs
Camera Zooming and Zoom Information Added: Issue [#86] (https://github.com/kk-digital/kcg/issues/86). You can check zoom rate value from the script inspector. Zooming works in both projections (perspective, orthographic). Ticket [#86](https://github.com/kk-digital/kcg/issues/86)
=> Camera Zooming and Zoom Information Added: Issue #86

Assets/Scripts/TilesRenderer.cs, Assets/src/TileProperties/TileCreationApi.cs, Assets/src/TileProperties/TilePropertiesData.cs, Assets/src/TileSpriteAtlas/SpriteAtlasManager.cs
Added Useful Comments;
Changed some code.
Added Tile Sprite Variant Array for TilePropertiesData;
=> Tile Sprite Variant Issue #84

Assets/Scripts/TilesRenderer.cs, Assets/src/GameManager/GameManager.cs, Assets/src/GameManager/GameState.cs, Assets/src/Physics/RectangleBoundingBoxCollision.cs, Assets/src/Sprites.meta, Assets/src/Sprites/SpriteAtlasManager.cs, Assets/src/Sprites/SpriteAtlasManager.cs.meta, Assets/src/Sprites/SpriteLoader.cs, Assets/src/Sprites/SpriteLoader.cs.meta, Assets/src/Tiles/TileProperties/TileCreationApi.cs, Assets/src/Tiles/TileSpriteAtlas/TileSpriteAtlas.cs, Assets/src/Tiles/TileSpriteAtlas/TileSpriteAtlas.cs.meta, Assets/src/Tiles/TileSpriteAtlas/TileSpriteAtlasManager.cs, Assets/src/Tiles/TileSpriteAtlas/TileSpriteAtlasManager.cs.meta
=> SpriteLoader/Atlas for Character Sprites

Assets/Scenes/MapTest.unity, Assets/Scenes/MapTest.unity.meta, Assets/Scenes/SpriteAtlasTest.unity, Assets/Scenes/SpriteAtlasTest.unity.meta, Assets/Scripts/MapLoaderTestScript.cs, Assets/Scripts/MapLoaderTestScript.cs.meta, Assets/Scripts/SpriteAtlasTest.cs, Assets/Scripts/SpriteAtlasTest.cs.meta, Assets/src/Sprites/SpriteAtlasManager.cs, Assets/src/Sprites/SpriteLoader.cs, Assets/src/Tiles/TileSpriteAtlas/TileSpriteAtlasManager.cs
Finished implementing the sprite loader / sprite atlas
Changed : TilesRenderer --> MapLoaderTestScript
Added a test Scene 'SpriteAtlasTest' to test out the sprite atlas
Added some comments in the code
=> Implement SpriteLoader/Atlas for Character Sprites #132

Assets/src/GameManager/GameState.cs, Assets/src/ecs/particles.meta, Assets/src/ecs/particles/ParticleComponents.cs, Assets/src/ecs/particles/ParticleComponents.cs.meta, Assets/src/ecs/particles/ParticleDrawSystem.cs.meta, Assets/src/ecs/particles/ParticleEmitterEntity.cs, Assets/src/ecs/particles/ParticleEmitterEntity.cs.meta, Assets/src/ecs/particles/ParticleList.cs, Assets/src/ecs/particles/ParticleList.cs.meta, Assets/src/ecs/particles/ParticleUpdateSystem.cs.meta
Particle System update:
ParticleComponents (implemented)
ParticleDrawSystem (not yet)
ParticleEmitterEntity (implemented / not complete)
ParticleUpdateSystem (not yet)
ParticleList  (implemented)
=> first particle systems update

Assets/Scenes/MapLoaderTest-MoonBunker.unity, Assets/Scripts/InputManager.cs
Main Scene Input Bugs Fixed. Ticket #147
=> Ticket #147: Main Scene Input Bugs Fixed

Assets/src/ecs/particles/ParticleComponents.cs, Assets/src/ecs/particles/ParticleEmitterEntity.cs, Assets/src/ecs/particles/ParticleList.cs, Assets/src/ecs/particles/ParticleUpdateSystem.cs
quick fix to the particle system
=> 2nd particle systems update

Assets/Scenes/ParticleTest.unity, Assets/Scenes/ParticleTest.unity.meta, Assets/Scripts/ParticlesTest.cs, Assets/Scripts/ParticlesTest.cs.meta, Assets/src/ecs/particles/ParticleComponents.cs, Assets/src/ecs/particles/ParticleDrawSystem.cs, Assets/src/ecs/particles/ParticleEmitterEntity.cs, Assets/src/ecs/particles/ParticleList.cs, Assets/src/ecs/particles/ParticleUpdateSystem.cs
ParticleUpdateSystem(complete)
Particle Test Scene (in progress)
=> second particle system commit

Assets/src/agents/components/VehicleComponentCollider.cs, Assets/src/agents/components/VehicleComponentCollider.cs.meta, Assets/src/agents/components/VehicleComponentDraw.cs, Assets/src/agents/components/VehicleComponentDraw.cs.meta, Assets/src/agents/entities/VehicleEntity.cs, Assets/src/agents/entities/VehicleEntity.cs.meta, Assets/src/agents/entities/VehicleList.cs, Assets/src/agents/entities/VehicleList.cs.meta, Assets/src/agents/systems/VehicleDrawSystem.cs, Assets/src/agents/systems/VehicleDrawSystem.cs.meta, Assets/src/agents/systems/VehiclePhysicsSystem.cs, Assets/src/agents/systems/VehiclePhysicsSystem.cs.meta
Files created, initializations are done.
=> Ticket #143: System Initialized

Assets/src/Item/Component/InventoryItemComponent.cs, Assets/src/Item/Component/ItemComponent.cs, Assets/src/ecs/Game/Particle/ParticleSpawn/GameObjectPosition.cs, Assets/src/ecs/Game/Particle/ParticleSpawn/ParticleComponent.cs, Assets/src/ecs/Game/Particle/ParticleSpawn/PositionComponent.cs
Better consistency. Also, [Game] attribute is redundant.
=> Remove [Game] attribute from Components

Assets/Scenes/Test/ProjectileRenderingTest.unity, Assets/Scenes/Test/ProjectileRenderingTest.unity.meta, Assets/Scripts/ProjectileTest.cs, Assets/Scripts/ProjectileTest.cs.meta, Assets/src/Projectile/Systems/ProjectileDrawSystem.cs
Projectile Draw Test Scene added. Issue #142
=> Projectile Draw Test Scene Added Issue #142

Assets/Scripts/AsmdefDebug.cs, Assets/Scripts/AsmdefDebug.cs.meta
Asmdef Debug Implemented. Issue #182
=> Asmdef Debug Implemented Issue #182

Assets/Scenes/Test/TileSpriteAtlasTest.unity, Assets/Scenes/Test/TileSpriteAtlasTest.unity.meta, Assets/Scripts/MapLoaderTestScript.cs, Assets/Scripts/TileSpriteAtlasTest.cs, Assets/Scripts/TileSpriteAtlasTest.cs.meta, Assets/src/Sprites/SpriteAtlasManager.cs, Assets/src/Tiles/PlanetTileMap/PlanetTileMap.cs, Assets/src/Tiles/TileProperties/PlanetLayer.cs, Assets/src/Tiles/TileProperties/PlanetTile.cs, Assets/src/Tiles/TileSpriteAtlas/TileSpriteAtlasManager.cs, Assets/src/Utility/RenderUtils.cs, Assets/src/Utility/RenderUtils.cs.meta, Assets/src/Utility/Sprite.cs, Assets/src/Utility/Sprite.cs.meta, Assets/src/Utility/TextureUtils.cs
Added a texture buffer to upload layer data for fast rendering in unity (think of it as a vbo)
Test Scene for TileSpriteAtlas
Added and ore layer and rendering support for multi layer tile map
=> back / mid / front / ore layers for PlanetTileMap

Assets/Scripts/ProjectileTest.cs, Assets/Scripts/VehicleTest.cs, Assets/src/Projectile/Systems/DrawSystem.cs, Assets/src/Vehicle/Systems/DrawSystem.cs
Vehicle Draw System Singleton Added Issue #143
=> Vehicle Draw System Singleton Added Issue #143

Assets/Scenes/Test/MapTest.unity, Assets/Scripts/MapLoaderTestScript.cs, Assets/src/Tiles/PlanetTileMap/PlanetTileMap.cs, Assets/src/Tiles/TileProperties/PlanetTile.cs, Assets/src/Tiles/TileProperties/TileCreationApi.cs, Assets/src/Tiles/TileProperties/TilePropertiesData.cs, Assets/src/Tiles/TileVariants.cs, Assets/src/Tiles/TileVariants.cs.meta
Tile Variant implementation 
Destroy tile in MapTest scene by clicking right mouse button
Todo: add comments to the code, fix the layers code, better naming conventions.
=> tile variant

Assets/Scripts/ProjectileTest.cs, Assets/Scripts/VehicleTest.cs, Assets/src/Projectile/Systems/DrawSystem.cs, Assets/src/Vehicle/List.cs, Assets/src/Vehicle/Systems/DrawSystem.cs, Assets/src/Vehicle/Systems/ProcessVelocitySystem.cs
=> Code Cleanup

Assets/Scripts/GameLoop.cs.meta, Assets/Scripts/InputManager.cs
Game Loop Material Bug Fixed Issue #222
=> Game Loop Material Bug Fixed Issue #222

Assets/Scripts/CameraInfo.cs, Assets/Source/Enum/WorldState.cs, Assets/Source/Enum/WorldState.cs.meta, Assets/Source/Vehicle/Systems/DrawSystem.cs, Assets/Source/Vehicle/Systems/ProcessVelocitySystem.cs, Assets/Source/World.meta, Assets/Source/World/WorldState.cs, Assets/Source/World/WorldState.cs.meta
=> Camera Enums Added Issue #207

Assets/Scenes/Test/RasterScanTest.unity, Assets/Scenes/Test/RasterScanTest.unity.meta, Assets/Scripts/RasterScanTest.cs, Assets/Scripts/RasterScanTest.cs.meta, Assets/Source/Math/RasterScan.meta, Assets/Source/Math/RasterScan/RasterScan.cs, Assets/Source/Math/RasterScan/RasterScan.cs.meta, Assets/Source/Math/RasterScan/Square.prefab, Assets/Source/Math/RasterScan/Square.prefab.meta
Raster scan draw line calculations added. Files added. Issue #235
=> Raster Scan Draw Line Calculations Added Issue #235

Assets/Entitas/Generated/Game/Components/GameAIActionComponent.cs, Assets/Scenes/Test/InventoryTest.unity, Assets/Scripts/AIGridWorldTest.cs, Assets/Scripts/ItemTest.cs, Assets/Source/AI/Actions.meta, Assets/Source/AI/Actions/IAction.cs, Assets/Source/AI/Actions/IAction.cs.meta, Assets/Source/AI/Components/ActionComponent.cs, Assets/Source/Enum/ActionState.cs, Assets/Source/Enum/ActionState.cs.meta, Assets/Source/Enum/WorldState.cs, Assets/Source/Inventory/Systems/DrawSystem.cs, Assets/Source/Utility/Render.cs
=> Inventory now draw stack count/base Action class for use items.

Assets/Scenes/Test/RasterScanTest.unity, Assets/Scripts/RasterScanTest.cs, Assets/Source/Math/RasterScan/Square.prefab
Raster Scan Test Scene Added. Use right click to shoot anywhere you want. Then see debug red squares to understand where you hit. Issue #238
=> Raster Scan Test Scene Added Issue #238

Assets/Scenes/Test/PlanetTest.unity, Assets/Scripts/AnimationTest.cs, Assets/Scripts/InventoryTest.cs, Assets/Scripts/ItemTest.cs, Assets/Scripts/MiningLaser.cs, Assets/Scripts/PlanetTest.cs, Assets/Scripts/SpawnEnemy.cs, Assets/Source/Animations/Animation.cs, Assets/Source/Enum/ItemType.cs, Assets/Source/Item/Systems/CreationApi.cs, Assets/Source/Sprites/SpriteAtlasManager.cs
toolbar tools added to planet test scene
4 tools are now working with the toolbar:
placement tool / remove tile tool / mining laser / spawn slime enemy
=> added toolbar tools

Assets/Scripts/ProjectileTest.cs, Assets/Scripts/RasterScanTest.cs, Assets/Source/Projectile/Systems/ProcessVelocitySystem.cs, Assets/Source/Projectile/Systems/SpawnerSystem.cs
Projectile Collision Raster Scan Updated to Chunks Issue #259
=> Projectile Collision Raster Scan Updated to Chunks Issue #259

Assets/Scenes/Test/PlanetVisualEffects.unity, Assets/Scripts/PlanetVisualEffectsTest.cs, Assets/Source/Planet/VisualEffects/PlanetBackgroundParallaxLayer.cs, Assets/Source/Planet/VisualEffects/PlanetBackgroundStarField.cs, Assets/Source/Planet/VisualEffects/PlanetBackgroundVisualEffects.cs, Assets/Source/Utility/Render.cs
Perlin Noise Star Generation Implemented Issue #210
=> Perlin Noise Star Generation Implemented

Assets/Scripts/Parallax.cs, Assets/Scripts/Parallax.cs.meta, Assets/Source/Planet/VisualEffects/PlanetBackgroundParallaxLayer.cs, Assets/Source/Planet/VisualEffects/PlanetBackgroundStarField.cs, Assets/Source/Planet/VisualEffects/PlanetBackgroundVisualEffects.cs
Parallax Implemented. Different types of stars added to list. Starfield updated. Issue #210
=> Background Parallax Implemented Issue #210

Assets/Scenes/Test/PlanetVisualEffects.unity, Assets/Scripts/GUIStatusTest.cs, Assets/Scripts/GUIStatusTest.cs.meta, Assets/Scripts/Parallax.cs, Assets/Scripts/ProjectileTest.cs, Assets/Source/GUI.meta, Assets/Source/GUI/HealthBarUI.cs, Assets/Source/GUI/HealthBarUI.cs.meta, Assets/Source/Planet/VisualEffects/PlanetBackgroundParallaxLayer.cs, Assets/Source/Planet/VisualEffects/PlanetBackgroundStarField.cs, Assets/Source/Projectile/Systems/ProcessCollisionSystem.cs, Assets/Source/Projectile/Systems/ProcessVelocitySystem.cs, Assets/Source/Projectile/Systems/SpawnerSystem.cs
Background Planets Added and Starfield Updated Issue #210
=> Background Planets Added and Starfield Updated Issue #210

Assets/Scripts/ProjectileTest.cs, Assets/Source/GUI/HealthBarUI.cs, Assets/Source/Utility/Render.cs
Annoying Health Bar Divide Bug Fixed Issue #249
=> Annoying Health Bar Divide Bug Fixed

Assets/Entitas/Generated/Game/Components/GameProjectilePosition2DComponent.cs, Assets/Scripts/ProjectileTest.cs, Assets/Source/Actions/ActionLogic/UseItem/FireWeaponAction.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/GameManager/GameState.cs, Assets/Source/Planet/PlanetState.cs, Assets/Source/Projectile/Component/Position2DComponent.cs, Assets/Source/Projectile/ProjectileCreationApi.cs, Assets/Source/Projectile/ProjectileCreationApi.cs.meta, Assets/Source/Projectile/ProjectileProperties.cs, Assets/Source/Projectile/ProjectileProperties.cs.meta, Assets/Source/Projectile/Systems/DrawSystem.cs, Assets/Source/Projectile/Systems/MovementSystem.cs, Assets/Source/Projectile/Systems/ProcessCollisionSystem.cs, Assets/Source/Projectile/Systems/ProcessVelocitySystem.cs, Assets/Source/Projectile/Systems/SpawnerSystem.cs
Projectile Creation Api
Projectile Rotation
Projectile Animation
Created Bullet like projectile using the api
Created Grenade like projectile using the api
=> projectile creation api

Assets/Scripts/GUIStatusTest.cs, Assets/Source/GUI/PlayerStatusGUI/FoodBarUI.cs, Assets/Source/GUI/PlayerStatusGUI/FuelBarUI.cs, Assets/Source/GUI/PlayerStatusGUI/OxygenBarUI.cs, Assets/Source/GUI/PlayerStatusGUI/WaterBarUI.cs
GUI Aspect Ratio Rescaling Added Issue #249
=> GUI Aspect Ratio Rescaling Added Issue #249

Assets/Entitas/Generated/Agent/Components/AgentAgentMovementStateComponent.cs, Assets/Source/Agents/Components/MovementStateComponent.cs, Assets/Source/Agents/Systems/AgentSpawnerSystem.cs, Assets/Source/Input/Systems/InputProcessSystem.cs, Assets/Source/Particles/Systems/MeshBuilderSystem.cs, Assets/Source/Utility/Mesh.cs
added rotation to the new rendering pipeline
=> Rotation Fix

Assets/Entitas/Generated/Agent/Components/AgentAgentMovementStateComponent.cs, Assets/Entitas/Generated/Agent/Components/AgentPhysicsMovableComponent.cs, Assets/Entitas/Generated/Components/Interfaces/IPhysicsMovableEntity.cs, Assets/Entitas/Generated/Item/Components/ItemPhysicsMovableComponent.cs, Assets/Source/Actions/ActionLogic/DropAction.cs, Assets/Source/Agents/Components/MovementStateComponent.cs, Assets/Source/Agents/Systems/AgentSpawnerSystem.cs, Assets/Source/Agents/Systems/EnemyAiSystem.cs, Assets/Source/Input/Systems/InputProcessSystem.cs, Assets/Source/Item/Systems/SpawnerSystem.cs, Assets/Source/Physics/Components/MovableComponent.cs, Assets/Source/Physics/Systems/PhysicsMovableSystem.cs, Assets/Source/PlanetTileMap/TileMap.cs
fixed the remove tile bug
dashing in mid air
added more gravity
values tweaking
fixed some movement bugs
=> movement changes

Assets/Source/Admin/AdminAPI.cs
Chunk Visualizer Updated. Issue #283
=> Chunk Visualizer Updated

Assets/Entitas/Generated/Components/Interfaces/IItemFireWeaponClipEntity.cs, Assets/Entitas/Generated/ItemInventory/Components/ItemInventoryItemFireWeaponChargeComponent.cs, Assets/Entitas/Generated/ItemInventory/Components/ItemInventoryItemFireWeaponClipComponent.cs, Assets/Entitas/Generated/ItemParticle/Components/ItemParticleItemFireWeaponClipComponent.cs, Assets/Scripts/Test/ItemTest.cs, Assets/Source/Actions/ActionLogic/ChargeAction.cs, Assets/Source/Actions/ActionLogic/ReloadAction.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionFireWeapon.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionThrowableGrenade.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionThrowableGrenade.cs.meta, Assets/Source/Actions/Systems/InitializeSystem.cs, Assets/Source/Enum/ActionType.cs, Assets/Source/Enum/ItemType.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/Item/Component.meta, Assets/Source/Item/Components/ChargeComponent.cs, Assets/Source/Item/Components/ClipComponent.cs, Assets/Source/Item/ItemCreationApi.cs, Assets/Source/Item/ItemProprieties.cs, Assets/Source/Item/Systems/SpawnerSystem.cs, Assets/Source/Projectile/Systems/ProcessCollisionSystem.cs
Charge Ratio Added. Issue #280
=> Charge Ratio Added Issue #280

Assets/Source/PlanetTileMap/TileMap.cs, Assets/Source/PlanetTileMap/TileMapRender.cs, Assets/Source/PlanetTileMap/TileMapping.cs
changing the tile rule from a lot of if statements to a single array lookup with an index (in progress)
=> new tile rule R3 (in progress)

Assets/Source/PlanetTileMap/SpriteRule_R1.cs, Assets/Source/PlanetTileMap/SpriteRule_R1.cs.meta, Assets/Source/PlanetTileMap/SpriteRule_R2.cs, Assets/Source/PlanetTileMap/SpriteRule_R2.cs.meta, Assets/Source/PlanetTileMap/SpriteRule_R3.cs, Assets/Source/PlanetTileMap/SpriteRule_R3.cs.meta, Assets/Source/PlanetTileMap/TileMap.cs
finished the implementation of R3
created a class for each rule
=> sprite rule R3 (complete)

Assets/Resources/DefaultHumanoid.prefab, Assets/Resources/DefaultHumanoid.prefab.meta, Assets/Scenes/Test/AnimancerTestScene.unity, Assets/Scripts/Test/AnimancerTestScript.cs
3d model created dynamically from unity prefab
to summarize:
1-load a 3d model
2-load animations
3-smooth change into any animation
=> Animancer test scene : model prefab instantiation

Assets/Scripts/Test/MechTest.cs, Assets/Source/Mech/Systems/MechSpawnSystem.cs
=> Fixed sprite id issue

Assets/Entitas/Generated/Mech/Components/MechMechPlanterPlanterComponent.cs, Assets/Scripts/Test/PlanterTest.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionPlanter.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/Mech/Components/PlanterComponent.cs, Assets/Source/Mech/MechType.cs, Assets/Source/Mech/Systems/MechSpawnSystem.cs
Light Level, Growth and Water Level Logic Implemented. You can give water to the pot. It will use water and light to grow plant. If there is no light near by pot. Then plant will not grow. Issue #419
=> Light Level, Growth and Water Level Logic Implemented

Assets/Source/Input/Systems/InputProcessSystem.cs
=> fix compile error

Assets/Entitas/Generated/Components/Interfaces/IItemCastDataEntity.cs, Assets/Entitas/Generated/ItemInventory/Components/ItemInventoryItemCastDataComponent.cs, Assets/Entitas/Generated/ItemParticle/Components/ItemParticleItemCastDataComponent.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionPlaceTile.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionScanner.cs, Assets/Source/Actions/Systems/InitializeSystem.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/GuiHud/GUI/Elements/Text.cs, Assets/Source/GuiHud/GUI/GUIManager.cs, Assets/Source/GuiHud/GUI/StatisticsDisplay/StatisticsDisplay.cs, Assets/Source/Input/Systems/InputProcessSystem.cs, Assets/Source/Item/Components/CastDataComponent.cs, Assets/Source/Item/Systems/SpawnerSystem.cs, Assets/Source/Mech/Systems/MechGUIDrawSystem.cs
Statics Display Optimized and Moved To HUD Overlay.
=> Statics Display Optimized and Moved To HUD Overlay

Assets/Source/Actions/ActionLogic/ToolAction/ToolActionMechPlacement.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionMechPlacement.cs.meta, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionRemoveMech.cs, Assets/Source/Actions/Systems/InitializeSystem.cs, Assets/Source/Enum/ActionType.cs, Assets/Source/Enum/ItemType.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/Item/Systems/SpawnerSystem.cs, Assets/Source/Planet/PlanetState.cs
Mech Drop API Added. Select the remove tool and click on any mech apart from plants. And it will pop out an item of it. You can place that item again anywhere you want. Issue #508
=> Mech Drop API Added

Assets/Scenes/Test/MovementScene.unity, Assets/Scripts/Test/MovementSceneScript.cs, Assets/Source/Agents/Systems/AgentSpawnerSystem.cs, Packages/manifest.json, Packages/packages-lock.json
Character Full Body IK Rig Initialized. Rig Setup. Bone Visualizer Setup. Issue #509
=> Character Full Body IK Rig Initialized

Assets/Scenes/Test/PlanetTest.unity, Assets/Scripts/Test/InventoryTest.cs, Assets/Scripts/Test/PlanetTest.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionFireWeapon.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionRemoveTile.cs, Assets/Source/Admin/AdminAPI.cs, Assets/Source/Enum/ItemType.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/FoodBarUI.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/FuelBarUI.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/HealthBarUI.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/OxygenBarUI.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/WaterBarUI.cs, Assets/Source/Inventory/CreationApi.cs
GUI Rescale Bugs Fixed.
ShowGUI bool added.
Issue #524
=> GUI Rescale Bugs Fixed

Assets/Entitas/Generated/Agent/Components/AgentAgentPhysicsStateComponent.cs, Assets/Resources/Stander.prefab, Assets/Scripts/Test/MovementSceneScript.cs, Assets/Scripts/Test/PlanetTest.cs, Assets/Source/Agents/AgentEntity.cs, Assets/Source/Agents/Components/PhysicsStateComponent.cs, Assets/Source/Agents/Systems/AgentSpawnerSystem.cs, Assets/Source/Agents/Systems/Model3DAnimationSystem.cs, Assets/Source/Agents/Systems/MovementSystem.cs, Assets/Source/Agents/Systems/ProcessCollisionSystem.cs, Assets/Source/Agents/Systems/ProcessPhysicalState.cs, Assets/Source/Collisions/TileCollisions.cs, Assets/Source/Engine3D/AnimationType.cs, Assets/Source/Engine3D/AssetManager.cs, Assets/Source/Enum/AgentMovementState.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/Input/Systems/InputProcessSystem.cs, Assets/Source/PlanetTileMap/TileCreationApi.cs
rolling mechanics
fixing ground friction
tile sprite update bug fix
=> rolling mechanics

Assets/Source/Agents/AgentEntity.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/Input/Systems/InputProcessSystem.cs, Assets/Source/Inventory/Systems/InventoryManager.cs, Assets/Source/Inventory/Systems/WindowScaleSystem.cs, Assets/Source/Item/ItemCreationApi.cs, Assets/Source/Item/ItemProprieties.cs, Assets/Source/Planet/PlanetState.cs
1) Fix chest/corpse bug
2) Fix bug related to stack count.
3) Fix bug where items disappear when move over another item.
4) Fix crash bug when trying to close all inventories with tab.
5) Fix bug where inventory doesn't returns to default position after closing chest.
=> Bug fixing

Assets/Entitas/Generated/Agent/Components/AgentAgentPhysicsStateComponent.cs, Assets/Source/Agents/AgentEntity.cs, Assets/Source/Agents/Components/PhysicsStateComponent.cs, Assets/Source/Agents/Systems/AgentSpawnerSystem.cs, Assets/Source/Agents/Systems/Model3DAnimationSystem.cs, Assets/Source/Agents/Systems/MouseInteractionSystem.cs, Assets/Source/Agents/Systems/ProcessCollisionSystem.cs, Assets/Source/Agents/Systems/ProcessPhysicalState.cs, Assets/Source/Engine3D/AnimationType.cs, Assets/Source/Engine3D/AssetManager.cs, Assets/Source/Enum/AgentMovementState.cs, Assets/Source/Input/Systems/InputProcessSystem.cs, Assets/Source/Particles/Systems/ParticleSpawnerSystem.cs
fixed the rolling and falling bug
crouch mecanics
crouch movement slow
crouching and rolling now have different hit box
=> Agent Movement : crouch

Assets/Scripts/Test/PlanetTest.cs, Assets/Source/Actions/ActionLogic/PickUpAction.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionHarvest.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionMeleeAttack.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionPlaceMaterial.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionPlaceMaterial.cs.meta, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionPlanter.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionPulseWeapon.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionRemoveTile.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionScanner.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionThrowableGrenade.cs, Assets/Source/Actions/ActionLogic/ToolAction/ToolActionWater.cs, Assets/Source/Actions/Systems/InitializeSystem.cs, Assets/Source/Enum/ActionType.cs, Assets/Source/Enum/ItemType.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/GuiHud/GUI/Elements/Image.cs, Assets/Source/GuiHud/GUI/GUIManager.cs, Assets/Source/Inventory/CreationApi.cs, Assets/Source/Item/Systems/SpawnerSystem.cs, Assets/Source/Mech/Systems/MouseInteractionSystem.cs, Assets/Source/Projectile/Systems/ProcessCollisionSystem.cs
Place Tile Tool Updated.
Material Bag Placed next inventory.
Dirt tile tested. Dirt count decrases when we place one.
When we out of dirt tool no more places dirt.
New Material Placement Tool Added/Initialized.
Issue #532
=> Place Tile Tool Updated

Assets/Source/Enum/ItemGroups.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/GuiHud/GUI/GUIManager.cs, Assets/Source/Input/Systems/InputProcessSystem.cs
Weapon Aiming Cursor Settings Implemented. Issue  #546
=> Weapon Aiming Cursor Settings Implemented

Assets/Scripts/Test/MechTest.cs, Assets/Source/Enum/ItemType.cs, Assets/Source/Enum/LootTableType.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/Inventory/Systems/MouseSelectionSystem.cs, Assets/Source/Inventory/Systems/WindowScaleSystem.cs, Assets/Source/Mech/MechType.cs, Assets/Source/Mech/Systems/MechGUIDrawSystem.cs
Complete.
Todo: create particles art for egg
Todo: create png icon for egg
=> Smashable egg

Assets/Source/GuiHud/GUI/Elements/Image.cs, Assets/Source/GuiHud/GUI/Elements/ProgressBar.cs, Assets/Source/GuiHud/GUI/Elements/Text.cs, Assets/Source/GuiHud/GUI/GUIManager.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/HealthBarUI.cs
Elements Optimized.
Cursor Disabled For now.
=> Elements Optimized

Assets/Scripts/Test/MovementSceneScript.cs, Assets/Source/Collisions/BroadPhaseAgentBoxTest.cs, Assets/Source/Collisions/BroadPhaseAgentBoxTest.cs.meta, Assets/Source/Collisions/BroadPhaseItemParticleBoxTest.cs, Assets/Source/Collisions/BroadPhaseItemParticleBoxTest.cs.meta, Assets/Source/Collisions/BroadPhaseParticleBoxTest.cs, Assets/Source/Collisions/BroadPhaseParticleBoxTest.cs.meta, Assets/Source/Collisions/BroadPhaseProjectileBoxTest.cs, Assets/Source/Collisions/BroadPhaseProjectileBoxTest.cs.meta, Assets/Source/Collisions/BroadphaseAgentCircleTest.cs, Assets/Source/Collisions/BroadphaseAgentCircleTest.cs.meta, Assets/Source/Collisions/BroadphaseItemParticleCircleTest.cs, Assets/Source/Collisions/BroadphaseItemParticleCircleTest.cs.meta, Assets/Source/Collisions/BroadphaseParticleCircleTest.cs, Assets/Source/Collisions/BroadphaseParticleCircleTest.cs.meta, Assets/Source/Collisions/BroadphaseProjectileCircleTest.cs, Assets/Source/Collisions/BroadphaseProjectileCircleTest.cs.meta, Assets/Source/Collisions/Collisions.cs, Assets/Source/Math/KMath.cs
-Broadphase for Agent test against Circle 
-Broadphase for Agent test against Box
-Broadphase for Item Particle test against Circle 
-Broadphase for Item Particle test against Box
-Broadphase for Particle test against Circle 
-Broadphase for Particle test against Box
-Broadphase for Projectile test against Circle 
-Broadphase for Projectile test against Box
=> Collision: Files for Broadphase

Assets/Source/GuiHud/GUI/Elements/Image.cs, Assets/Source/GuiHud/GUI/GUIManager.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/FoodBarUI.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/FuelBarUI.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/HealthBarUI.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/OxygenBarUI.cs, Assets/Source/GuiHud/GUI/PlayerStatusGUI/WaterBarUI.cs, Assets/Source/Planet/PlanetState.cs, Assets/Source/Utility/DrawDebug.cs
"Exit", "Enter" called every frame fixed
Now only "Stay" event called every frame
"Enter" called once cursor inside ui icon
"Exit" called once cursor outside of ui icon
=> Fixed Gui Manager

Assets/Source/Actions/ActionLogic/ToolAction/ToolActionGasBomb.cs, Assets/Source/GameManager/GameResources.cs, Assets/Source/Particles/CircleSmoke/CircleSmoke.cs
Circle Spawn Crash Bug Fixed.
Issue #556
=> Circle Spawn Crash Bug Fixed

Assets/Scripts/Test/MovementSceneScript.cs, Assets/Source/Collisions/RayCastAgainstCircle.cs, Assets/Source/Collisions/RayCastAgainstCircle.cs.meta, Assets/Source/Collisions/RayCastAgainstTileMapCircle.cs, Assets/Source/Collisions/RayCastAgainstTileMapCircle.cs.meta, Assets/Source/Collisions/RayCastResult.cs, Assets/Source/Collisions/RayCastResult.cs.meta, Assets/Source/GameManager/GameResources.cs, Assets/Source/Projectile/Systems/ProcessCollisionSystem.cs
ray casting again terrain AABB moving along line segment
=> ray casting again terrain AABB moving along line segment

Assets/Scripts/Test/InventoryTest.cs, Assets/Scripts/Test/MapLoaderTestScript.cs, Assets/Scripts/Test/PlanetVisualEffectsTest.cs, Assets/Scripts/Test/ProjectileTest.cs, Assets/Scripts/Test/SpriteAtlasTest.cs, Assets/Source/Planet/PlanetState.cs, Assets/Source/Sprites/SpriteAtlasManager.cs
added comments and removed unnecessary code
=> sprite atlas changes

Assets/Resources/ArtistAnimations/MediumMarine/GunAlerted.anim, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolAlerted.controller, Assets/Resources/Shinabro/Platform_Animation/Animator/05_Pistol/Pistol_Attack.controller, Assets/Scenes/Test/IKTestScene.unity, Assets/Source/Agents/SpaceMarineAnimations.cs
IK Rig Bug Fixes.
Char shuttering research
Animation settings updated.
We might need avatar masking or animacer component change. IK rig is not normal on character.
Issue #706
=> IK Rig Bug Fixes

Assets/Resources/ArtistAnimations/SpaceMarine/GunIdle.anim, Assets/Resources/MediumMarinePrefab.prefab, Assets/Resources/Pistol.prefab, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolAlerted.anim, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolAlerted.anim.meta, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolAlerted.controller, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolIdle.anim, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolIdle.anim.meta, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolRun.anim, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolRun.anim.meta, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolShoot.anim, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolShoot.anim.meta, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolWalking.anim, Assets/Resources/Polygonmaker/Polygonmaker Animations/Regular/Scenes/Source/Animators for render/PistolWalking.anim.meta, Assets/Scenes/Test/IKTestScene.unity, Assets/Scenes/Test/MovementScene.unity, Assets/Source/Agents/AgentEntity.cs, Assets/Source/Agents/Systems/AgentIKSystem.cs, Assets/Source/Agents/Systems/Model3DAnimationSystem.cs, Assets/Source/Agents/Systems/Model3DMovementSystem.cs
Rifle IK Bugs Fixed.
Pistol Hand IK initialized.
Issue #706
=> Rifle IK Bugs Fixed

Assets/Entitas/Generated/Agent/Components/AgentAgentModel3DComponent.cs, Assets/Resources/MediumMarinePrefab.prefab, Assets/Scenes/Test/GeometryTest.unity, Assets/Scripts/CameraFollow.cs, Assets/Scripts/Test/TiledTest.cs, Assets/Source/Agents/AgentEntity.cs, Assets/Source/Agents/Components/Model3DComponent.cs, Assets/Source/Agents/Systems/AgentIKSystem.cs, Assets/Source/Agents/Systems/AgentSpawnerSystem.cs, Assets/Source/Agents/Systems/Model3DMovementSystem.cs, Assets/Source/Vehicle/Systems/AISystem.cs, Assets/Source/Vehicle/Systems/SpawnerSystem.cs, Assets/Source/Vehicle/VehicleCreationApi.cs
SetAimTarget function added.
Issue #706
=> SetAimTarget function added

Assets/Resources/MediumMarinePrefab.prefab, Assets/Source/Agents/AgentEntity.cs, Assets/Source/Agents/Systems/AgentIKSystem.cs, Assets/Source/Agents/Systems/ProcessStats.cs, Assets/Source/Vehicle/Systems/AISystem.cs
Demo Tweaks Added.
Gun dissapaers after enemy/player die.
IK separated procudural to anim when dead.
Dropship members get off from ship with random velocity (pops out). Weapon fire postition fixed. And set to right hand standard. Issue #706
=> Demo Tweaks Added

Assets/Plugins/RootMotion/FinalIK/_Integration/IK Jobs (Unity 2018.2.4f1).unitypackage.meta, Assets/Plugins/RootMotion/FinalIK/_Integration/IK Jobs (Unity 2019.3).unitypackage.meta, Assets/Plugins/RootMotion/FinalIK/_Integration/Oculus (Unity 2017.4.28f1, Oculus Integration v1.37).unitypackage.meta, Assets/Plugins/RootMotion/FinalIK/_Integration/Playmaker (Unity 2017.4.28f1, PlayMaker 1.9.0).unitypackage.meta, Assets/Plugins/RootMotion/FinalIK/_Integration/ReadyPlayerMe (Unity 2018.4.28f1, Oculus Integration).unitypackage.meta, Assets/Plugins/RootMotion/FinalIK/_Integration/Steam VR (Unity 2017.4.28f1, SteamVR Plugin v2.6.1).unitypackage.meta, Assets/Plugins/RootMotion/FinalIK/_Integration/UMA (Unity 2017.4.28f1, UMA 2.8.1).unitypackage.meta, Assets/Plugins/RootMotion/FinalIK/_Integration/VRIK Movement Animset Pro.unitypackage.meta, Assets/Plugins/RootMotion/FinalIK/_Integration/VRIK Photon Demo (Unity 2017.4.28f1, Oculus Integration, PUN 1.103).unitypackage.meta, Assets/Plugins/RootMotion/FinalIK/_Integration/VRIK Photon2 Demo (Unity 2017.4.28f1, Oculus or SteamVR Integration, PUN 2.20.2).unitypackage.meta, Assets/Plugins/RootMotion/Import Assembly Definitions.unitypackage.meta, Assets/Scripts/Test/TiledTest.cs, Assets/Source/Particles/CircleSmoke/CircleSmoke.cs, Assets/Source/Vehicle/Pod/PodCreationApi.cs, Assets/Source/Vehicle/Pod/Systems/AISystem.cs
Drop Pod Landing Implemented.
Drop pod lands and stops before 2m.
Explodes and panels fly through environment.
Explosion particle added.
AI system changed for tis manner.
Issue #706
=> Drop Pod Landing Implemented

Assets/Source/Planet/PlanetState.cs, Assets/Source/Vehicle/Pod/PodCreationApi.cs, Assets/Source/Vehicle/Pod/PodProperties.cs, Assets/Source/Vehicle/Pod/Systems/AISystem.cs, Assets/Source/Vehicle/Pod/Systems/SpawnerSystem.cs
Drop Pod Updates.
Enemies drop out with velocity.
Pod falls thorugh after explosion.
Issue #706
=> Drop Pod Updates

Assets/Scripts/Test/TiledTest.cs, Assets/Source/Physics/Constants.cs, Assets/Source/Projectile/Systems/MovementSystem.cs, Assets/Source/Projectile/Systems/ProcessOnHit.cs, Assets/Source/Vehicle/Pod/PodCreationApi.cs, Assets/Source/Vehicle/Pod/Systems/AISystem.cs, Assets/Source/Vehicle/Pod/Systems/MeshBuilderSystem.cs, Assets/Source/Vehicle/Pod/Systems/ProcessCollisionSystem.cs
Drop Pod Implemented.
Drop pod gets close to the ground and explodes.
Panels fly through the environment.
Main part falls ground and enemies cams out of it. with a velocity pop out. Issue #706
=> Drop Pod Implemented

Assets/Source/AI/Deprecated/Nodes/Actions/ToolAction/ToolActionConstruction.cs, Assets/Source/AI/Deprecated/Nodes/Actions/ToolAction/ToolActionPlaceTile.cs
Invalid Build Tools Fixed.
closes #941 resolves #941
=> Invalid Build Tools Fixed

Assets/Source/AI/BehaviorTree/BehaviorTreeExecute.cs, Assets/Source/Agents/AgentEntity.cs, Assets/Source/Agents/Systems/ProcessPhysicalState.cs, Assets/Source/Item/ItemCreationApi.cs, Assets/Source/Projectile/Systems/ProcessOnHit.cs, Assets/_Karl/Scenes/Game Launcher.unity, Assets/_Karl/Scenes/Main.unity, Assets/_Karl/Scripts/Player/Player.cs, Assets/_Karl/Scripts/Player/PlayerInputStandalone.cs
Stagger System, Compiler Errors Bug Fixes.
Stagger system fixed. Changed to disable controls.
Bullet don't hit bug fixed.
Stagger duration fixed.
Compiler Errors Fixed
Issue #706
=> Stagger System, Compiler Errors Bug Fixes
